In [1]:
import numpy as np

In [5]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array((1,2,3))))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
np.zeros(5) # un solo numero para un arreglo
np.zeros([5,5]) # una lsita o tupla para una matriz de n dimensiones
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.arange(5)
np.arange(4,20) #el número de la derecha es abierto, rango [4,20[
np.arange(-12, 1) #toma desde el negativo
np.arange(0,2.1,0.5) #el 2do número del intervalo siempre es abierto

<class 'numpy.ndarray'>


In [18]:
np.arange(10).reshape(2,5).shape

(2, 5)

In [20]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [26]:
a * b

array([50, 50, 50])

In [27]:
a % 3

array([1, 1, 1], dtype=int32)

In [36]:
muestra = np.arange(20).reshape(5,2,2)

In [32]:
res_gl = muestra > 5

In [34]:
res_gl

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [35]:
muestra[res_gl]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
A = np.arange(4).reshape((2,2))
B = np.arange(4).reshape((2,2))

In [6]:
A.dot(B)
B.dot(A)

array([[ 2,  3],
       [ 6, 11]])

In [8]:
np.dot(A,B)
np.dot(B,A)

array([[ 2,  3],
       [ 6, 11]])

In [10]:
arreglo_doce = np.arange(12)

In [11]:
arreglo_doce.sum()

66

In [13]:
arreglo_doce.min()
arreglo_doce.max()

11

In [14]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [16]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [17]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])