In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array([0,30,45,60,90])

In [5]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [6]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [7]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [8]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [14]:
numero_random = np.random.randint(11) #[0, 11[
numero_random

6

In [16]:
numero_random_neg = np.random.randint(-9, 2)
numero_random_neg

-3

In [19]:
arreglo_random = np.random.randint(10, 20, 8)
arreglo_random

array([17, 12, 12, 16, 16, 15, 14, 11])

In [20]:
np.average(arreglo_random) #promedio

14.125

In [21]:
np.mean(arreglo_random) #media

14.125

In [22]:
np.median(arreglo_random) #mediana

14.5

In [24]:
np.std(arreglo_random) #desviacion estandar

2.0879116360612584