In [1]:
import numpy as np

In [2]:
arreglo = np.arange(11) ** 2
arreglo

In [9]:
arreglo[0:7]
arreglo[-6:-1]
arreglo[2:]
arreglo[:-3]
arreglo[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
arreglo[0:6]

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [12]:
arreglo[0:6:2]

array([ 0,  4, 16], dtype=int32)

In [13]:
arreglo[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)